version: "2"

services:
    frontend:
        container_name: react_frontend
        build:
            context: react_project
            dockerfile: Dockerfile
        ports:
            - 8080:80
        depends_on:
            - backend

    backend:
        container_name: node_backend
        build:
            context: backend_server
            dockerfile: Dockerfile.dev
        volumes:
            - ./backend_server:/app:rw
        ports:
            - 3000:3000
        env_file:
            - ./backend_server/config.env
